[features]
seeds = false
skip-lint = false

[programs.localnet]
safe_shipping = "Ab8n8gyf9YT4gMwW84HaoAsJwJisbsHa5Z9L7AVxpC4y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
